"""MiDRR API — FastAPI application entry point.

Start the server locally:
    uvicorn api.main:app --reload

The --reload flag makes the server restart automatically when you edit
a file (like nodemon in Node.js).

Interactive docs (auto-generated by FastAPI):
    http://localhost:8000/docs      ← Swagger UI
    http://localhost:8000/redoc     ← ReDoc
"""

from fastapi import FastAPI

from api.routes.predict import router as predict_router
from api.routes.session import router as session_router

app = FastAPI(
    title="MiDRR API",
    description=(
        "REST API for the MiDRR-Classifier — predicts student disaster preparedness "
        "level (HIGH / MODERATE / LOW) from Minecraft simulation session features."
    ),
    version="0.1.0",
)

app.include_router(predict_router)
app.include_router(session_router)


@app.get("/health", tags=["health"])
def health() -> dict:
    """Health check endpoint. Returns 200 if the server is running."""
    return {"status": "ok"}
